spring:
  datasource:
    url: jdbc:mysql://localhost:3306/az_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 200312Zwx
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  main:
    allow-circular-references: true

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
server:
  port: 7777

oss:
  accessKey: ZJG_QPXnRIP2FZ_65Zdu-zDxHOIsRKtDDCDFKAu2
  secretKey: sqjBB0Uose-fsVQ9nEPYMAbXstkrXK6JhIZ4XF5p
  bucket: az-blog
  domainName: rumyn3ucc.bkt.clouddn.com/